### ISSUE TITLE
Execution of /usr/share/munin/plugins/queue_ aborted due to compilation errors

### ISSUE THREAD

**Issue by fenidik** [kipsnak/munin-activemq-plugin#1]
/usr/share/munin/plugins/queue_ autoconf
Type of arg 1 to keys must be hash (not hash element) at /usr/share/munin/plugins/queue_ line 232, near "} )"
Type of arg 1 to keys must be hash (not hash element) at /usr/share/munin/plugins/queue_ line 245, near "})"
Type of arg 1 to values must be hash (not private array) at /usr/share/munin/plugins/queue_ line 268, near "@vars_array)"
Type of arg 1 to keys must be hash (not private variable) at /usr/share/munin/plugins/queue_ line 269, near "$hash )"
Execution of /usr/share/munin/plugins/queue_ aborted due to compilation errors.

OS Debian

**Comment by labynocle** [comment]
You right there is a little issue about it.
I quick fix it by a tiny workaround that you can find on my fork: https://github.com/labynocle/munin-activemq-plugin

@kipsnak told me I will fix it as soon as possible but if you can't wait you can use my fork :)

**Comment by fenidik** [comment]
@labynocle thanks

**Comment by kipsnak** [comment]
@fenidik @labynocle sorry but I can't reproduce this error. It seems working properly under Archlinux:
I'll test it on Debian environment as soon as possible ...

I fixed another error in the last commit: about fetch env variable from munin-node when munin launch.

> /usr/share/munin/plugins/queue_ autoconf
> yes

here examples:

> $ munin-run queue_first_foo 
> enqueueCount.value 1
> dequeueCount.value 0
> 
> $ munin-run queue_test 
> size.value 1
> enqueueCount.value 1
> dequeueCount.value 0

sha1sum /usr/share/munin/plugins/queue_
e55f50c1804519cf9614e9249cfd6b029907105c  /usr/share/munin/plugins/queue_

**Comment by kipsnak** [comment]
@fenidik which perl version are you using ? it works with: perl 5, version 16, subversion 2 (v5.16.2)

**Comment by fenidik** [comment]
@kipsnak 5.10.1-17squeeze3 package installed

**Comment by labynocle** [comment]
with the latest commit it works for me (a least the autoconf test - because now I use my fork :P)

update: my env:
- perl 5.10.1-17squeeze4

**Comment by isnotajoke** [comment]
Checking in with the same issue on Perl 5.8.8.

The changes in https://github.com/isnotajoke/munin-activemq-plugin/commit/d60577af20dc2946904253ee30dce48b605fa490 resolve the issue on my installation.

**Comment by kipsnak** [comment]
@fenidik can you try @isnotajoke's fork and tell me if it's working for you ? big thanks to @isnotajoke !

**Comment by fenidik** [comment]
@kipsnak yep. @isnotajoke's fork works fine for me. Thanks guys.
