### ISSUE TITLE
Using 'infra' instead of 'info' in graph config confuses Munin

### ISSUE THREAD

**Issue by isnotajoke** [kipsnak/munin-activemq-plugin#2]
The configuration hash for the dequeueCount graph has the key 'infra', which apparently isn't expected by Munin, and causes a warning when the plugin is run by munin-node. Changing the key from 'infra' to 'info' resolves the issue on my setup. 

I fixed the issue on my fork: https://github.com/isnotajoke/munin-activemq-plugin/commit/50c57750a7c9fa679d832f4b3aca1c246d67a006

Thanks for your work on the plugin.

**Comment by kipsnak** [comment]
All thanks goes to you :+1:
